sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- 11.6.0
before_script:
- npm install
script:
- npm run test:ci
- npm run e2e:ci
- npm run build
deploy:
  provider: heroku
  api_key:
    secure: n04miU8/99BhkrVMlNMXF39TXTJDOjhFjAbyO7hSPfB1Ori2WhpwUA5HVhPD/OGZdPfW8op7DH6epQlD4eyZPAnKud0rVaYdAGDpj1nxvwiAXfRTrHoNgBl3b9vtDJsFpf5XHa11YZ30sgPAnEsIw6rcTreHMO/XI1K4jQfb1yipRZGQ83LijGSgukQMtj9eWIuTSTXySWe8BIxr0djYwxVe02YhU4xdut9+jiibSCT/ynZjZOwLh0x9VdqUz/KM9gc5u6REyY6wagkrxZxktYaPl86ZrbNYCt9IuFvlxJpLm7Qyu7GQQELW8lbbicQ8b11QOEYNwGY9G6TKWeJc89zgaJDdfACaa3Evun9yrkme6Xp/u8+5nMt7Nx3X4lhCCjzteGnRhmhESiH51KPC4j+JNxDA+Jy0p0c/BASDpQAn2FqBhMgofsoWvqUISZbmGMGdxUQXk3hv1qQnm2ZRUPAR624BwlFcI6iKHvltVgX30qn7sJ2VtH+WMgtirex05PksO/uRsM9sy0v+PesJrNrYAIveQhdWpnpHwE3fcx0oIPRnn5GFmW6ZWxapXldfW8umTWYyZXV+LkIxQQt9ZqkPyjeGWCRv2KDetwOGcSUbDvRceMwonQMF1oxxVsAkfUJ6brfQljUg4UD7yU6h5YcybW0V8R56LxgkOuMUxSQ=
  skip_cleanup: false
